// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ProvaPub.Repository;

#nullable disable

namespace ProvaPub.Migrations
{
    [DbContext(typeof(TestDbContext))]
    [Migration("20230422174403_Init")]
    partial class Init
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ProvaPub.Models.Customer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Customers");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Alonzo Volkman"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Allan Greenfelder"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Irving Huels"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Jane Balistreri"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Edward Cole"
                        },
                        new
                        {
                            Id = 6,
                            Name = "Susan Nader"
                        },
                        new
                        {
                            Id = 7,
                            Name = "Pete Goodwin"
                        },
                        new
                        {
                            Id = 8,
                            Name = "Veronica Bartoletti"
                        },
                        new
                        {
                            Id = 9,
                            Name = "Ron Fadel"
                        },
                        new
                        {
                            Id = 10,
                            Name = "Angelina Greenfelder"
                        },
                        new
                        {
                            Id = 11,
                            Name = "Evelyn Zieme"
                        },
                        new
                        {
                            Id = 12,
                            Name = "Alberto Schuppe"
                        },
                        new
                        {
                            Id = 13,
                            Name = "Marian Streich"
                        },
                        new
                        {
                            Id = 14,
                            Name = "Roland Windler"
                        },
                        new
                        {
                            Id = 15,
                            Name = "Lee Ryan"
                        },
                        new
                        {
                            Id = 16,
                            Name = "Megan Boyer"
                        },
                        new
                        {
                            Id = 17,
                            Name = "Marcia Homenick"
                        },
                        new
                        {
                            Id = 18,
                            Name = "Cedric Upton"
                        },
                        new
                        {
                            Id = 19,
                            Name = "Vicki Ferry"
                        },
                        new
                        {
                            Id = 20,
                            Name = "Irving Cronin"
                        });
                });

            modelBuilder.Entity("ProvaPub.Models.Order", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CustomerId")
                        .HasColumnType("int");

                    b.Property<DateTime>("OrderDate")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("Value")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("CustomerId");

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("ProvaPub.Models.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Tasty Steel Car"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Handmade Soft Mouse"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Handcrafted Cotton Salad"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Fantastic Steel Soap"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Incredible Concrete Computer"
                        },
                        new
                        {
                            Id = 6,
                            Name = "Licensed Metal Tuna"
                        },
                        new
                        {
                            Id = 7,
                            Name = "Tasty Fresh Pizza"
                        },
                        new
                        {
                            Id = 8,
                            Name = "Incredible Frozen Ball"
                        },
                        new
                        {
                            Id = 9,
                            Name = "Refined Rubber Salad"
                        },
                        new
                        {
                            Id = 10,
                            Name = "Rustic Metal Tuna"
                        },
                        new
                        {
                            Id = 11,
                            Name = "Gorgeous Wooden Table"
                        },
                        new
                        {
                            Id = 12,
                            Name = "Sleek Steel Bacon"
                        },
                        new
                        {
                            Id = 13,
                            Name = "Unbranded Plastic Chicken"
                        },
                        new
                        {
                            Id = 14,
                            Name = "Rustic Steel Pants"
                        },
                        new
                        {
                            Id = 15,
                            Name = "Rustic Cotton Shirt"
                        },
                        new
                        {
                            Id = 16,
                            Name = "Sleek Wooden Sausages"
                        },
                        new
                        {
                            Id = 17,
                            Name = "Incredible Fresh Chips"
                        },
                        new
                        {
                            Id = 18,
                            Name = "Handcrafted Frozen Bacon"
                        },
                        new
                        {
                            Id = 19,
                            Name = "Handcrafted Metal Chair"
                        },
                        new
                        {
                            Id = 20,
                            Name = "Generic Wooden Towels"
                        });
                });

            modelBuilder.Entity("ProvaPub.Models.Order", b =>
                {
                    b.HasOne("ProvaPub.Models.Customer", "Customer")
                        .WithMany("Orders")
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Customer");
                });

            modelBuilder.Entity("ProvaPub.Models.Customer", b =>
                {
                    b.Navigation("Orders");
                });
#pragma warning restore 612, 618
        }
    }
}
